/*globals define*/
/*eslint-env node, browser*/

/**
 * Generated by PluginGenerator 2.20.5 from webgme on Sat Nov 29 2025 10:45:15 GMT-0600 (Central Standard Time).
 * A plugin that inherits from the PluginBase. To see source code documentation about available
 * properties and methods visit %host%/docs/source/PluginBase.html.
 */

define([
    'plugin/PluginConfig',
    'text!./metadata.json',
    'plugin/PluginBase'
], function (
    PluginConfig,
    pluginMetadata,
    PluginBase) {
    'use strict';

    pluginMetadata = JSON.parse(pluginMetadata);

    /**
     * Initializes a new instance of PlayAudio.
     * @class
     * @augments {PluginBase}
     * @classdesc This class represents the plugin PlayAudio.
     * @constructor
     */
    function PlayAudio() {
        // Call base class' constructor.
        PluginBase.call(this);
        this.pluginMetadata = pluginMetadata;
    }

    /**
     * Metadata associated with the plugin. Contains id, name, version, description, icon, configStructure etc.
     * This is also available at the instance at this.pluginMetadata.
     * @type {object}
     */
    PlayAudio.metadata = pluginMetadata;

    // Prototypical inheritance from PluginBase.
    PlayAudio.prototype = Object.create(PluginBase.prototype);
    PlayAudio.prototype.constructor = PlayAudio;

    /**
     * Main function for the plugin to execute. This will perform the execution.
     * Notes:
     * - Always log with the provided logger.[error,warning,info,debug].
     * - Do NOT put any user interaction logic UI, etc. inside this method.
     * - callback always has to be called even if error happened.
     *
     * @param {function(Error|null, plugin.PluginResult)} callback - the result callback
     */
    PlayAudio.prototype.main = function (callback) {
        // Use this to access core, project, result, logger etc from PluginBase.
        const self = this;
        const logger = this.logger;
        const activeNode = self.activeNode;

        self.invokePlugin('audioGraphToJson')
            .then((result) => {
                if (result.getSuccess() !== true) {
                    throw new Error('audioGraphToJson did not return');
                }

                const moFileHash = result.getArtifacts()[0];

                self.result.addArtifact(moFileHash);

                return self.blobClient.getObjectAsString(moFileHash);
            })
            .then((moFileContent) => {
                //logger.info(moFileContent);
            })
            .catch((err) => {
                // Result success is false at invocation.
                self.logger.error(err.stack);
                callback(err, self.result);
            });
    };

    return PlayAudio;
});
