// DO NOT EDIT THIS FILE
// This file is automatically generated from the webgme-setup-tool.
'use strict';

var config = require('webgme/config/config.default'),
  validateConfig = require('webgme/config/validator');

// The paths can be loaded from the webgme-setup.json
config.plugin.basePaths.push(__dirname + '/../src/plugins');
config.plugin.allowBrowserExecution = true;

// Visualizer descriptors
config.visualization.visualizerDescriptors.push(__dirname + '/../src/visualizers/Visualizers.json');

// Add requirejs paths
config.requirejsPaths = Object.assign({}, config.requirejsPaths, {
  'web-audio': './src/common',
  'panels': './src/visualizers/panels'
});

config.mongo.uri = 'mongodb://127.0.0.1:27017/web_audio';
validateConfig(config);
module.exports = config;
